/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWorkspacesWorkspaceIdRouteImport } from './routes/_authenticated/workspaces.$workspaceId'
import { Route as AuthenticatedDatasetsDatasetIdRouteImport } from './routes/_authenticated/datasets_.$datasetId'
import { Route as ApiPublicHooksJobsTickRouteImport } from './routes/api/public/hooks/jobs-tick'
import { Route as AuthenticatedDatasetsDatasetIdReportsRouteImport } from './routes/_authenticated/datasets_.$datasetId.reports'
import { Route as AuthenticatedDatasetsDatasetIdForecastRouteImport } from './routes/_authenticated/datasets_.$datasetId.forecast'
import { Route as AuthenticatedDatasetsDatasetIdChatRouteImport } from './routes/_authenticated/datasets_.$datasetId.chat'
import { Route as AuthenticatedDatasetsDatasetIdAnomaliesRouteImport } from './routes/_authenticated/datasets_.$datasetId.anomalies'
import { Route as AuthenticatedDatasetsDatasetIdAnalysisRouteImport } from './routes/_authenticated/datasets_.$datasetId.analysis'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspacesWorkspaceIdRoute =
  AuthenticatedWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => AuthenticatedWorkspacesRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdRoute =
  AuthenticatedDatasetsDatasetIdRouteImport.update({
    id: '/datasets_/$datasetId',
    path: '/datasets/$datasetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksJobsTickRoute = ApiPublicHooksJobsTickRouteImport.update({
  id: '/api/public/hooks/jobs-tick',
  path: '/api/public/hooks/jobs-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDatasetsDatasetIdReportsRoute =
  AuthenticatedDatasetsDatasetIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedDatasetsDatasetIdRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdForecastRoute =
  AuthenticatedDatasetsDatasetIdForecastRouteImport.update({
    id: '/forecast',
    path: '/forecast',
    getParentRoute: () => AuthenticatedDatasetsDatasetIdRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdChatRoute =
  AuthenticatedDatasetsDatasetIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedDatasetsDatasetIdRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdAnomaliesRoute =
  AuthenticatedDatasetsDatasetIdAnomaliesRouteImport.update({
    id: '/anomalies',
    path: '/anomalies',
    getParentRoute: () => AuthenticatedDatasetsDatasetIdRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdAnalysisRoute =
  AuthenticatedDatasetsDatasetIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedDatasetsDatasetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren
  '/datasets/$datasetId': typeof AuthenticatedDatasetsDatasetIdRouteWithChildren
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRoute
  '/datasets/$datasetId/analysis': typeof AuthenticatedDatasetsDatasetIdAnalysisRoute
  '/datasets/$datasetId/anomalies': typeof AuthenticatedDatasetsDatasetIdAnomaliesRoute
  '/datasets/$datasetId/chat': typeof AuthenticatedDatasetsDatasetIdChatRoute
  '/datasets/$datasetId/forecast': typeof AuthenticatedDatasetsDatasetIdForecastRoute
  '/datasets/$datasetId/reports': typeof AuthenticatedDatasetsDatasetIdReportsRoute
  '/api/public/hooks/jobs-tick': typeof ApiPublicHooksJobsTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren
  '/datasets/$datasetId': typeof AuthenticatedDatasetsDatasetIdRouteWithChildren
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRoute
  '/datasets/$datasetId/analysis': typeof AuthenticatedDatasetsDatasetIdAnalysisRoute
  '/datasets/$datasetId/anomalies': typeof AuthenticatedDatasetsDatasetIdAnomaliesRoute
  '/datasets/$datasetId/chat': typeof AuthenticatedDatasetsDatasetIdChatRoute
  '/datasets/$datasetId/forecast': typeof AuthenticatedDatasetsDatasetIdForecastRoute
  '/datasets/$datasetId/reports': typeof AuthenticatedDatasetsDatasetIdReportsRoute
  '/api/public/hooks/jobs-tick': typeof ApiPublicHooksJobsTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren
  '/_authenticated/datasets_/$datasetId': typeof AuthenticatedDatasetsDatasetIdRouteWithChildren
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRoute
  '/_authenticated/datasets_/$datasetId/analysis': typeof AuthenticatedDatasetsDatasetIdAnalysisRoute
  '/_authenticated/datasets_/$datasetId/anomalies': typeof AuthenticatedDatasetsDatasetIdAnomaliesRoute
  '/_authenticated/datasets_/$datasetId/chat': typeof AuthenticatedDatasetsDatasetIdChatRoute
  '/_authenticated/datasets_/$datasetId/forecast': typeof AuthenticatedDatasetsDatasetIdForecastRoute
  '/_authenticated/datasets_/$datasetId/reports': typeof AuthenticatedDatasetsDatasetIdReportsRoute
  '/api/public/hooks/jobs-tick': typeof ApiPublicHooksJobsTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/datasets'
    | '/workspaces'
    | '/datasets/$datasetId'
    | '/workspaces/$workspaceId'
    | '/datasets/$datasetId/analysis'
    | '/datasets/$datasetId/anomalies'
    | '/datasets/$datasetId/chat'
    | '/datasets/$datasetId/forecast'
    | '/datasets/$datasetId/reports'
    | '/api/public/hooks/jobs-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/datasets'
    | '/workspaces'
    | '/datasets/$datasetId'
    | '/workspaces/$workspaceId'
    | '/datasets/$datasetId/analysis'
    | '/datasets/$datasetId/anomalies'
    | '/datasets/$datasetId/chat'
    | '/datasets/$datasetId/forecast'
    | '/datasets/$datasetId/reports'
    | '/api/public/hooks/jobs-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/datasets'
    | '/_authenticated/workspaces'
    | '/_authenticated/datasets_/$datasetId'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/datasets_/$datasetId/analysis'
    | '/_authenticated/datasets_/$datasetId/anomalies'
    | '/_authenticated/datasets_/$datasetId/chat'
    | '/_authenticated/datasets_/$datasetId/forecast'
    | '/_authenticated/datasets_/$datasetId/reports'
    | '/api/public/hooks/jobs-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicHooksJobsTickRoute: typeof ApiPublicHooksJobsTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesRoute
    }
    '/_authenticated/datasets_/$datasetId': {
      id: '/_authenticated/datasets_/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/jobs-tick': {
      id: '/api/public/hooks/jobs-tick'
      path: '/api/public/hooks/jobs-tick'
      fullPath: '/api/public/hooks/jobs-tick'
      preLoaderRoute: typeof ApiPublicHooksJobsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/datasets_/$datasetId/reports': {
      id: '/_authenticated/datasets_/$datasetId/reports'
      path: '/reports'
      fullPath: '/datasets/$datasetId/reports'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdReportsRouteImport
      parentRoute: typeof AuthenticatedDatasetsDatasetIdRoute
    }
    '/_authenticated/datasets_/$datasetId/forecast': {
      id: '/_authenticated/datasets_/$datasetId/forecast'
      path: '/forecast'
      fullPath: '/datasets/$datasetId/forecast'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdForecastRouteImport
      parentRoute: typeof AuthenticatedDatasetsDatasetIdRoute
    }
    '/_authenticated/datasets_/$datasetId/chat': {
      id: '/_authenticated/datasets_/$datasetId/chat'
      path: '/chat'
      fullPath: '/datasets/$datasetId/chat'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdChatRouteImport
      parentRoute: typeof AuthenticatedDatasetsDatasetIdRoute
    }
    '/_authenticated/datasets_/$datasetId/anomalies': {
      id: '/_authenticated/datasets_/$datasetId/anomalies'
      path: '/anomalies'
      fullPath: '/datasets/$datasetId/anomalies'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdAnomaliesRouteImport
      parentRoute: typeof AuthenticatedDatasetsDatasetIdRoute
    }
    '/_authenticated/datasets_/$datasetId/analysis': {
      id: '/_authenticated/datasets_/$datasetId/analysis'
      path: '/analysis'
      fullPath: '/datasets/$datasetId/analysis'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdAnalysisRouteImport
      parentRoute: typeof AuthenticatedDatasetsDatasetIdRoute
    }
  }
}

interface AuthenticatedWorkspacesRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
}

const AuthenticatedWorkspacesRouteChildren: AuthenticatedWorkspacesRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdRoute:
      AuthenticatedWorkspacesWorkspaceIdRoute,
  }

const AuthenticatedWorkspacesRouteWithChildren =
  AuthenticatedWorkspacesRoute._addFileChildren(
    AuthenticatedWorkspacesRouteChildren,
  )

interface AuthenticatedDatasetsDatasetIdRouteChildren {
  AuthenticatedDatasetsDatasetIdAnalysisRoute: typeof AuthenticatedDatasetsDatasetIdAnalysisRoute
  AuthenticatedDatasetsDatasetIdAnomaliesRoute: typeof AuthenticatedDatasetsDatasetIdAnomaliesRoute
  AuthenticatedDatasetsDatasetIdChatRoute: typeof AuthenticatedDatasetsDatasetIdChatRoute
  AuthenticatedDatasetsDatasetIdForecastRoute: typeof AuthenticatedDatasetsDatasetIdForecastRoute
  AuthenticatedDatasetsDatasetIdReportsRoute: typeof AuthenticatedDatasetsDatasetIdReportsRoute
}

const AuthenticatedDatasetsDatasetIdRouteChildren: AuthenticatedDatasetsDatasetIdRouteChildren =
  {
    AuthenticatedDatasetsDatasetIdAnalysisRoute:
      AuthenticatedDatasetsDatasetIdAnalysisRoute,
    AuthenticatedDatasetsDatasetIdAnomaliesRoute:
      AuthenticatedDatasetsDatasetIdAnomaliesRoute,
    AuthenticatedDatasetsDatasetIdChatRoute:
      AuthenticatedDatasetsDatasetIdChatRoute,
    AuthenticatedDatasetsDatasetIdForecastRoute:
      AuthenticatedDatasetsDatasetIdForecastRoute,
    AuthenticatedDatasetsDatasetIdReportsRoute:
      AuthenticatedDatasetsDatasetIdReportsRoute,
  }

const AuthenticatedDatasetsDatasetIdRouteWithChildren =
  AuthenticatedDatasetsDatasetIdRoute._addFileChildren(
    AuthenticatedDatasetsDatasetIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRouteWithChildren
  AuthenticatedDatasetsDatasetIdRoute: typeof AuthenticatedDatasetsDatasetIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRouteWithChildren,
  AuthenticatedDatasetsDatasetIdRoute:
    AuthenticatedDatasetsDatasetIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicHooksJobsTickRoute: ApiPublicHooksJobsTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
