/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkspacesRouteImport } from './routes/_authenticated/workspaces'
import { Route as AuthenticatedDatasetsRouteImport } from './routes/_authenticated/datasets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWorkspacesWorkspaceIdRouteImport } from './routes/_authenticated/workspaces.$workspaceId'
import { Route as AuthenticatedDatasetsDatasetIdRouteImport } from './routes/_authenticated/datasets_.$datasetId'
import { Route as AuthenticatedDatasetsDatasetIdForecastRouteImport } from './routes/_authenticated/datasets_.$datasetId.forecast'
import { Route as AuthenticatedDatasetsDatasetIdChatRouteImport } from './routes/_authenticated/datasets_.$datasetId.chat'
import { Route as AuthenticatedDatasetsDatasetIdAnomaliesRouteImport } from './routes/_authenticated/datasets_.$datasetId.anomalies'
import { Route as AuthenticatedDatasetsDatasetIdAnalysisRouteImport } from './routes/_authenticated/datasets_.$datasetId.analysis'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspacesRoute = AuthenticatedWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatasetsRoute = AuthenticatedDatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspacesWorkspaceIdRoute =
  AuthenticatedWorkspacesWorkspaceIdRouteImport.update({
    id: '/$workspaceId',
    path: '/$workspaceId',
    getParentRoute: () => AuthenticatedWorkspacesRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdRoute =
  AuthenticatedDatasetsDatasetIdRouteImport.update({
    id: '/datasets_/$datasetId',
    path: '/datasets/$datasetId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdForecastRoute =
  AuthenticatedDatasetsDatasetIdForecastRouteImport.update({
    id: '/forecast',
    path: '/forecast',
    getParentRoute: () => AuthenticatedDatasetsDatasetIdRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdChatRoute =
  AuthenticatedDatasetsDatasetIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => AuthenticatedDatasetsDatasetIdRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdAnomaliesRoute =
  AuthenticatedDatasetsDatasetIdAnomaliesRouteImport.update({
    id: '/anomalies',
    path: '/anomalies',
    getParentRoute: () => AuthenticatedDatasetsDatasetIdRoute,
  } as any)
const AuthenticatedDatasetsDatasetIdAnalysisRoute =
  AuthenticatedDatasetsDatasetIdAnalysisRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedDatasetsDatasetIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren
  '/datasets/$datasetId': typeof AuthenticatedDatasetsDatasetIdRouteWithChildren
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRoute
  '/datasets/$datasetId/analysis': typeof AuthenticatedDatasetsDatasetIdAnalysisRoute
  '/datasets/$datasetId/anomalies': typeof AuthenticatedDatasetsDatasetIdAnomaliesRoute
  '/datasets/$datasetId/chat': typeof AuthenticatedDatasetsDatasetIdChatRoute
  '/datasets/$datasetId/forecast': typeof AuthenticatedDatasetsDatasetIdForecastRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/datasets': typeof AuthenticatedDatasetsRoute
  '/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren
  '/datasets/$datasetId': typeof AuthenticatedDatasetsDatasetIdRouteWithChildren
  '/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRoute
  '/datasets/$datasetId/analysis': typeof AuthenticatedDatasetsDatasetIdAnalysisRoute
  '/datasets/$datasetId/anomalies': typeof AuthenticatedDatasetsDatasetIdAnomaliesRoute
  '/datasets/$datasetId/chat': typeof AuthenticatedDatasetsDatasetIdChatRoute
  '/datasets/$datasetId/forecast': typeof AuthenticatedDatasetsDatasetIdForecastRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/datasets': typeof AuthenticatedDatasetsRoute
  '/_authenticated/workspaces': typeof AuthenticatedWorkspacesRouteWithChildren
  '/_authenticated/datasets_/$datasetId': typeof AuthenticatedDatasetsDatasetIdRouteWithChildren
  '/_authenticated/workspaces/$workspaceId': typeof AuthenticatedWorkspacesWorkspaceIdRoute
  '/_authenticated/datasets_/$datasetId/analysis': typeof AuthenticatedDatasetsDatasetIdAnalysisRoute
  '/_authenticated/datasets_/$datasetId/anomalies': typeof AuthenticatedDatasetsDatasetIdAnomaliesRoute
  '/_authenticated/datasets_/$datasetId/chat': typeof AuthenticatedDatasetsDatasetIdChatRoute
  '/_authenticated/datasets_/$datasetId/forecast': typeof AuthenticatedDatasetsDatasetIdForecastRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/datasets'
    | '/workspaces'
    | '/datasets/$datasetId'
    | '/workspaces/$workspaceId'
    | '/datasets/$datasetId/analysis'
    | '/datasets/$datasetId/anomalies'
    | '/datasets/$datasetId/chat'
    | '/datasets/$datasetId/forecast'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/dashboard'
    | '/datasets'
    | '/workspaces'
    | '/datasets/$datasetId'
    | '/workspaces/$workspaceId'
    | '/datasets/$datasetId/analysis'
    | '/datasets/$datasetId/anomalies'
    | '/datasets/$datasetId/chat'
    | '/datasets/$datasetId/forecast'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/datasets'
    | '/_authenticated/workspaces'
    | '/_authenticated/datasets_/$datasetId'
    | '/_authenticated/workspaces/$workspaceId'
    | '/_authenticated/datasets_/$datasetId/analysis'
    | '/_authenticated/datasets_/$datasetId/anomalies'
    | '/_authenticated/datasets_/$datasetId/chat'
    | '/_authenticated/datasets_/$datasetId/forecast'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspaces': {
      id: '/_authenticated/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AuthenticatedWorkspacesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets': {
      id: '/_authenticated/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof AuthenticatedDatasetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspaces/$workspaceId': {
      id: '/_authenticated/workspaces/$workspaceId'
      path: '/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AuthenticatedWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedWorkspacesRoute
    }
    '/_authenticated/datasets_/$datasetId': {
      id: '/_authenticated/datasets_/$datasetId'
      path: '/datasets/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/datasets_/$datasetId/forecast': {
      id: '/_authenticated/datasets_/$datasetId/forecast'
      path: '/forecast'
      fullPath: '/datasets/$datasetId/forecast'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdForecastRouteImport
      parentRoute: typeof AuthenticatedDatasetsDatasetIdRoute
    }
    '/_authenticated/datasets_/$datasetId/chat': {
      id: '/_authenticated/datasets_/$datasetId/chat'
      path: '/chat'
      fullPath: '/datasets/$datasetId/chat'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdChatRouteImport
      parentRoute: typeof AuthenticatedDatasetsDatasetIdRoute
    }
    '/_authenticated/datasets_/$datasetId/anomalies': {
      id: '/_authenticated/datasets_/$datasetId/anomalies'
      path: '/anomalies'
      fullPath: '/datasets/$datasetId/anomalies'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdAnomaliesRouteImport
      parentRoute: typeof AuthenticatedDatasetsDatasetIdRoute
    }
    '/_authenticated/datasets_/$datasetId/analysis': {
      id: '/_authenticated/datasets_/$datasetId/analysis'
      path: '/analysis'
      fullPath: '/datasets/$datasetId/analysis'
      preLoaderRoute: typeof AuthenticatedDatasetsDatasetIdAnalysisRouteImport
      parentRoute: typeof AuthenticatedDatasetsDatasetIdRoute
    }
  }
}

interface AuthenticatedWorkspacesRouteChildren {
  AuthenticatedWorkspacesWorkspaceIdRoute: typeof AuthenticatedWorkspacesWorkspaceIdRoute
}

const AuthenticatedWorkspacesRouteChildren: AuthenticatedWorkspacesRouteChildren =
  {
    AuthenticatedWorkspacesWorkspaceIdRoute:
      AuthenticatedWorkspacesWorkspaceIdRoute,
  }

const AuthenticatedWorkspacesRouteWithChildren =
  AuthenticatedWorkspacesRoute._addFileChildren(
    AuthenticatedWorkspacesRouteChildren,
  )

interface AuthenticatedDatasetsDatasetIdRouteChildren {
  AuthenticatedDatasetsDatasetIdAnalysisRoute: typeof AuthenticatedDatasetsDatasetIdAnalysisRoute
  AuthenticatedDatasetsDatasetIdAnomaliesRoute: typeof AuthenticatedDatasetsDatasetIdAnomaliesRoute
  AuthenticatedDatasetsDatasetIdChatRoute: typeof AuthenticatedDatasetsDatasetIdChatRoute
  AuthenticatedDatasetsDatasetIdForecastRoute: typeof AuthenticatedDatasetsDatasetIdForecastRoute
}

const AuthenticatedDatasetsDatasetIdRouteChildren: AuthenticatedDatasetsDatasetIdRouteChildren =
  {
    AuthenticatedDatasetsDatasetIdAnalysisRoute:
      AuthenticatedDatasetsDatasetIdAnalysisRoute,
    AuthenticatedDatasetsDatasetIdAnomaliesRoute:
      AuthenticatedDatasetsDatasetIdAnomaliesRoute,
    AuthenticatedDatasetsDatasetIdChatRoute:
      AuthenticatedDatasetsDatasetIdChatRoute,
    AuthenticatedDatasetsDatasetIdForecastRoute:
      AuthenticatedDatasetsDatasetIdForecastRoute,
  }

const AuthenticatedDatasetsDatasetIdRouteWithChildren =
  AuthenticatedDatasetsDatasetIdRoute._addFileChildren(
    AuthenticatedDatasetsDatasetIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatasetsRoute: typeof AuthenticatedDatasetsRoute
  AuthenticatedWorkspacesRoute: typeof AuthenticatedWorkspacesRouteWithChildren
  AuthenticatedDatasetsDatasetIdRoute: typeof AuthenticatedDatasetsDatasetIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatasetsRoute: AuthenticatedDatasetsRoute,
  AuthenticatedWorkspacesRoute: AuthenticatedWorkspacesRouteWithChildren,
  AuthenticatedDatasetsDatasetIdRoute:
    AuthenticatedDatasetsDatasetIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
